/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.2.0/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}


include("application", "engine", "buffer", "index", "storage", "catalog", "commons", "integration")
project(":application").projectDir = file("modules/application/")
project(":engine").projectDir = file("modules/engine/")
project(":buffer").projectDir = file("modules/buffer/")
project(":index").projectDir = file("modules/index/")
project(":storage").projectDir = file("modules/storage/")
project(":catalog").projectDir = file("modules/catalog/")
project(":commons").projectDir = file("commons/")
project(":integration").projectDir = file("integration/")
